# frozen_string_literal: true

module A2a
  module Types
    # Represents a file, data structure, or other resource generated by an agent during a task
    class Artifact < BaseModel
      attr_accessor :artifact_id, :name, :description, :parts, :extensions

      def initialize(attributes = {})
        super
        @artifact_id = attributes[:artifact_id] || attributes["artifactId"]
        @name = attributes[:name] || attributes["name"]
        @description = attributes[:description] || attributes["description"]
        parts_data = attributes[:parts] || attributes["parts"]
        @parts = if parts_data
                   parts_data.map do |part|
                     part.is_a?(Part) ? part : Part.new(part)
                   end
                 end
        @extensions = attributes[:extensions] || attributes["extensions"]
      end
    end
  end
end
